package com.applitracc.backend.api;

public enum ErrorCode {

    USER_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    COLUMN_NOT_FOUND,
    MAX_COLUMNS_EXCEEDED,
    VALIDATION_ERROR,
    UNAUTHORIZED_ACCESS,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    INTERNAL_ERROR
}
