spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/applitrack
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
# The secret key is just a dummy value for development purposes.
jwt.secret=dGhpcyBpcyBhIHRlc3Qgc2VjcmV0IGtleSBmb3IgZGV2ZWxvcG1lbnQgb25seQ==
jwt.expiration=86400000